sozluk = {
    "melankoli": "melancholy",
    "hüzün": "sorrow",
    "ihtişam": "magnificence",
    "özlemler": "yearnings",
    "serüven": "adventure",
    "büyüleyici": "captivating",
    "dokunaklı": "touching",
    "intikam": "revenge",
    "saflık": "purity",
    "zarafet": "elegance",
    "tezat": "contrast",
    "depresyon": "depression",
    "huzur": "serenity",
    "direniş": "resistance",
    "kader": "fate",
    "ilham": "inspiration",
    "aşkın hali": "state of love",
    "sükunet": "quietude",
    "nefes": "breath",
    "şairane": "poetical",
    "istiklal": "independence",
    "bıkkınlık": "weariness",
    "yazgı": "destiny",
    "deneyim": "experience",
    "sessizlik": "silence",
    "ihtişamlı": "grandiose",
    "neşve": "bliss",
    "beyhude": "futile",
    "hasret": "nostalgia",
    "sahtelik": "falseness",
    "kıskanmak": "envy",
    "kabullenmek": "acceptance",
    "gizem": "mystery",
    "sanat": "art",
    "Zenci":"nigga",
    "Beyefendi":"Gentlemen",
    "özgürlük": "freedom",
    "dostluk": "friendship",
    "barış": "peace",
    "sevda": "passion",
    "huzur": "peacefulness",
    "hayal": "dream",
    "gökyüzü": "sky",
    "rüya": "dream",
    "gülüş": "smile",
    "bahar": "spring",
    "savaş": "war",
    "zarafet": "grace",
    "mutluluk": "happiness",
    "neşe": "joy",
    "özgürlük": "liberty",
    "yolculuk": "journey",
    "deniz": "sea",
    "sıcaklık": "warmth",
    "göç": "migration",
    "sonbahar": "autumn",
    "zaman": "time",
    "gölge": "shadow",
    "çözüm": "solution",
    "aydınlık": "brightness",
    "fırtına": "storm",
    "aşk": "love",
    "umut": "hope",
    "özlem": "longing",
    "güzellik": "beauty",
    "merhaba": "hello",
    "kitap": "book",
    "ev": "house",
    "araba": "car",
    "bilgisayar": "computer",
    "televizyon": "television",
    "mutfak": "kitchen",
    "okul": "school",
    "sevgili": "beloved",
    "barkod": "barcode",

}

print(sozluk.keys())
secim=str(input("Lütfen bir kelime seçiniz : "))
print(secim," Kelimesinin İngilizcesi : ",sozluk[secim])
print("Bizi tercih ettiğiniz için teşekkür ederiz...")